name: tubes_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0  # Untuk menggunakan font custom seperti Pacifico
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^17.2.4
  permission_handler: ^11.3.0
  image_picker: ^1.0.4
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  path: ^1.9.0
  http: ^1.2.1
  crypto: ^3.0.3
  cloudinary: ^1.0.0
  cloudinary_public: ^0.21.0
  provider: ^6.0.5 
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0 
  firebase_messaging: ^15.1.0
  shimmer: ^2.0.0
  flutter_rating_bar: ^4.0.1 
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"

  assets:
    - assets/images/CotoMakassar.jpeg
    - assets/images/gado-gado.jpeg
    - assets/images/Gudeg.jpeg
    - assets/images/kerakTelur.jpeg
    - assets/images/Konro.jpeg
    - assets/images/MieAceh.jpeg
    - assets/images/papeda.jpeg
    - assets/images/rawon.jpeg
    - assets/images/rendang.jpeg
    - assets/images/SotoAyam.jpeg