// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7q50JpCG1B1hr63de7NaiBI_0sV8Zqlo',
    appId: '1:809082747922:web:4ae1719d7d63a817f7accb',
    messagingSenderId: '809082747922',
    projectId: 'dapoerkita-19699',
    authDomain: 'dapoerkita-19699.firebaseapp.com',
    storageBucket: 'dapoerkita-19699.firebasestorage.app',
    measurementId: 'G-K2EF5DDJCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoIcSYHaNhqWMK0wM5PMlkA9eFagYyNwA',
    appId: '1:809082747922:android:e44b3c1172aa7c3ef7accb',
    messagingSenderId: '809082747922',
    projectId: 'dapoerkita-19699',
    storageBucket: 'dapoerkita-19699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCFte50BFOMt86ac74woOl5alPklT5svI',
    appId: '1:809082747922:ios:a9fc970fb549548ef7accb',
    messagingSenderId: '809082747922',
    projectId: 'dapoerkita-19699',
    storageBucket: 'dapoerkita-19699.firebasestorage.app',
    iosClientId: '809082747922-t54k2l6dsf9bmfgfc57m98325bbnq850.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubes1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCFte50BFOMt86ac74woOl5alPklT5svI',
    appId: '1:809082747922:ios:a9fc970fb549548ef7accb',
    messagingSenderId: '809082747922',
    projectId: 'dapoerkita-19699',
    storageBucket: 'dapoerkita-19699.firebasestorage.app',
    iosClientId: '809082747922-t54k2l6dsf9bmfgfc57m98325bbnq850.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubes1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7q50JpCG1B1hr63de7NaiBI_0sV8Zqlo',
    appId: '1:809082747922:web:074abdfab6bedd43f7accb',
    messagingSenderId: '809082747922',
    projectId: 'dapoerkita-19699',
    authDomain: 'dapoerkita-19699.firebaseapp.com',
    storageBucket: 'dapoerkita-19699.firebasestorage.app',
    measurementId: 'G-PY9K5FELEJ',
  );
}
